name: PR:5.x

on:
  pull_request:
    branches:
      - 5.x

jobs:
  ARM64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-5.x-ARM64.yaml@main

  U20:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-5.x-U20.yaml@main

  W10:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-5.x-W10.yaml@main

  macOS-ARM64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-5.x-macOS-ARM64.yaml@main

  macOS-X64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-5.x-macOS-x86_64.yaml@main

  iOS:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-5.x-iOS.yaml@main

  TIM-VX:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-timvx-backend-tests-4.x.yml@main